stages:
  - sync
  - create
  - release

include:
  - local: .gitlab/.gitlab-ci.build.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_DRIVER: overlay2
  BUILDX_VERSION: v${DOCKER_BUILDX_VERSION}
  BUILDX_ARCHITECTURE: linux-arm64
  DOCKER_CREDENTIAL_HELPER_VERSION: v${DOCKER_CRED_HELPER_VERSION}
  DOCKER_CREDENTIAL_HELPER_ARCHITECTURE: linux-arm64  
  IMAGE_NAME: "movim"
  MOVIM_REPOSITORY: "https://github.com/movim/movim.git"
  CI_REGISTRY_IMAGE: ravermeister/${IMAGE_NAME}
  GALENER_REPOSITORY: "https://github.com/jech/galene"  
  GPG_USER: movim-ci
  GPG_MAIL: info@rimkus.it  
  DOCKER_AUTH_CONFIG: '
    {
      "credsStore": "pass"
    }
  '

.init_versions:
  env_vars:
    - export MOVIM_VERSION=$(awk -F= 'NR==1 {print $2}' VERSION)    
    - export GALENE_TASKS_VISION_VERSION=$(awk -F= 'NR==2 {print $2}' VERSION)

.init_alpine_docker:
  init_docker:
    - !reference [.init_versions, env_vars]
    - apk add --no-cache make bash curl libsecret pass gpg-agent openssh-client
    - .gitlab/docker-credential-init.sh "${GPG_USER}" "${GPG_MAIL}"
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCHITECTURE
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - mkdir -p /usr/local/bin
    - curl -sSLo /usr/local/bin/docker-credential-pass https://github.com/docker/docker-credential-helpers/releases/download/$DOCKER_CREDENTIAL_HELPER_VERSION/docker-credential-pass-$DOCKER_CREDENTIAL_HELPER_VERSION.$DOCKER_CREDENTIAL_HELPER_ARCHITECTURE
    - chmod +x /usr/local/bin/docker-credential-pass
    - docker context create tls-environment >/dev/null
    - docker buildx create --use tls-environment >/dev/null
    - echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json
    - echo "${CI_REGISTRY_PASSWORD}" | awk '{print $0}' | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  logout:
    - docker logout

.init_alpine_golang:
  init_env:
    - !reference [.init_versions, env_vars]
    - apk add --no-cache wget tar git
  shutdown: []
    # commands as array below
    
