stages:
  - sync
  - create
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILDKIT_STEP_LOG_MAX_SIZE: "-1"
  BUILDKIT_COMMAND_KEEP_ALIVE: "120m"
  DOCKER_DRIVER: overlay2
  BUILDX_VERSION: v${DOCKER_BUILDX_VERSION}
  BUILDX_ARCHITECTURE: linux-arm64
  IMAGE_NAME: "movim"
  MOVIM_REPOSITORY: "https://github.com/movim/movim.git"
  CI_REGISTRY_IMAGE: ravermeister/${IMAGE_NAME}
  GALENE_REPOSITORY: "https://github.com/jech/galene"  
  GALENE_PACKAGE_BASE_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/galene"
  GALENE_KEEP_VERSIONS: 3 # Maximal zu behaltende Versionen

.init_versions:
  env_vars:
    - export MOVIM_VERSION=$(awk -F= 'NR==1 {print $2}' VERSION)  # line 1 is movim_version
    - export GALENE_VERSION=$(awk -F= 'NR==2 {print $2}' VERSION) # line 2 is galene_version
    - export GALENE_TASKS_VISION_VERSION=$(awk -F= 'NR==3 {print $2}' VERSION) # line 3 is tasks_vision_version

.init_alpine_docker:
  init_docker:
    - !reference [.init_versions, env_vars]
    - apk add --no-cache make bash curl
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCHITECTURE
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker context create tls-environment >/dev/null
    - docker buildx create --name gitlab-builder --use tls-environment >/dev/null    
    - echo "${CI_REGISTRY_PASSWORD}" | awk '{print $0}' | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}" 2>/dev/null
  logout:
    - docker logout

.init_alpine_golang:
  init_env:
    - !reference [.init_versions, env_vars]
    - apk add --no-cache wget tar git
  shutdown: []
    # commands as array below

include:
  - local: .gitlab/.gitlab-ci.build.tpl.yml
  - local: .gitlab/.gitlab-ci.build.amd64.yml
  - local: .gitlab/.gitlab-ci.build.arm64.yml
    
