### galene arm64
galene_arm64:
  stage: create
  extends: .galene
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.rimkus.it"

### create arm64
image_arm64:
  extends: .dind
  stage: create
  dependencies: 
    - galene_arm64
  needs: 
    - galene_arm64
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.rimkus.it"
  script:    
    - echo "build Movim Version $MOVIM_VERSION"
    - >
      docker buildx build --no-cache --force-rm --compress --load \
        --platform "linux/arm64" \
        --build-arg MOVIM_GIT_REPO=$MOVIM_REPOSITORY \
        --build-arg MOVIM_VERSION=$MOVIM_VERSION \
        -t "${IMAGE_NAME}" \
        -t "${CI_REGISTRY_IMAGE}:arm64" \
        --target movim-arm64 \
        .
    - docker push "${CI_REGISTRY_IMAGE}:arm64"

### add arm64 to manifest
manifest_arm64:
  extends: .dind
  stage: release
  dependencies: [ ]
  needs:
    - image_arm64
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.rimkus.it"
  script:    
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:arm64"  
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:${MOVIM_VERSION}" "${CI_REGISTRY_IMAGE}:arm64"
    # append possible amd64
    - docker buildx imagetools create --append --tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:amd64"  
    - docker buildx imagetools create --append --tag "${CI_REGISTRY_IMAGE}:${MOVIM_VERSION}" "${CI_REGISTRY_IMAGE}:amd64"
