# docker in docker template
.dind:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  tags:
    - docker
    - arm64
  before_script:
    - apk add --no-cache make bash curl libsecret pass gpg-agent openssh-client
    - .gitlab/docker-credential-init.sh "${GPG_USER}" "${GPG_MAIL}"
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCHITECTURE
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - mkdir -p /usr/local/bin
    - curl -sSLo /usr/local/bin/docker-credential-pass https://github.com/docker/docker-credential-helpers/releases/download/$DOCKER_CREDENTIAL_HELPER_VERSION/docker-credential-pass-$DOCKER_CREDENTIAL_HELPER_VERSION.$DOCKER_CREDENTIAL_HELPER_ARCHITECTURE
    - chmod +x /usr/local/bin/docker-credential-pass
    - docker context create tls-environment >/dev/null
    - docker buildx create --use tls-environment >/dev/null
    - echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json
    - echo "${CI_REGISTRY_PASSWORD}" | awk '{print $0}' | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  after_script:
    - docker logout

####################################

### create arm64
image_arm64:
  extends: .dind
  stage: create
  dependencies: []
  needs: []
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.rimkus.it"
  script:
    - movim_version=$(cat VERSION)
    - echo "build Movim Version $movim_version"
    - >
      docker buildx build --no-cache --force-rm --compress --load \
        --platform "linux/arm64" \
        --build-arg MOVIM_GIT_REPO=$MOVIM_REPOSITORY \
        --build-arg MOVIM_VERSION=$movim_version \
        -t "${IMAGE_NAME}" \
        -t "${CI_REGISTRY_IMAGE}:arm64" \
        --target movim-arm64 \
        .
    - docker push "${CI_REGISTRY_IMAGE}:arm64"

### create arm64
image_amd64:
  extends: .dind
  stage: create
  tags:
    - gitlab-org-docker
  dependencies: []
  needs: []
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.com"
  script:
    - movim_version=$(cat VERSION)
    - echo "build Movim Version $movim_version"
    - >
      docker buildx build --no-cache --force-rm --compress --load \
        --platform "linux/amd64" \
        --build-arg MOVIM_GIT_REPO=$MOVIM_REPOSITORY \
        --build-arg MOVIM_VERSION=$movim_version \
        -t "${IMAGE_NAME}" \
        -t "${CI_REGISTRY_IMAGE}:amd64" \
        --target movim-amd64 \
        .
    - docker push "${CI_REGISTRY_IMAGE}:amd64"


### add tags to manifest
manifest:
  extends: .dind
  stage: release
  dependencies: [ ]
  needs:
    - image_arm64
  rules:
    - if: $CI_SERVER_URL == "https://gitlab.rimkus.it"
  script:
    - movim_version=$(cat VERSION)
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:arm64"  
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:${movim_version}" "${CI_REGISTRY_IMAGE}:arm64"
